import type { Achievement } from "@/types";

export const ACHIEVEMENT_SEED: Achievement[] = [
  {
    id: "first_log",
    code: "first_log",
    title: "First Forge",
    description: "Log your first meal.",
    xpReward: 50,
    pointsReward: 25,
    tier: "bronze",
  },
  {
    id: "streak_3",
    code: "streak_3",
    title: "Kindling",
    description: "Hit a 3-day logging streak.",
    xpReward: 75,
    pointsReward: 40,
    tier: "bronze",
  },
  {
    id: "streak_7",
    code: "streak_7",
    title: "Week on Fire",
    description: "Maintain a 7-day logging streak.",
    xpReward: 150,
    pointsReward: 80,
    tier: "silver",
  },
  {
    id: "streak_30",
    code: "streak_30",
    title: "Unbreakable",
    description: "Maintain a 30-day logging streak.",
    xpReward: 400,
    pointsReward: 200,
    tier: "gold",
  },
  {
    id: "water_7",
    code: "water_7",
    title: "Hydrated",
    description: "Hit your water target 7 days in a row.",
    xpReward: 120,
    pointsReward: 60,
    tier: "silver",
  },
  {
    id: "weigh_in_4",
    code: "weigh_in_4",
    title: "Honest Scale",
    description: "Complete 4 weigh-ins.",
    xpReward: 100,
    pointsReward: 50,
    tier: "silver",
  },
  {
    id: "macro_perfect",
    code: "macro_perfect",
    title: "Split Shot",
    description: "Hit all three macros in one day.",
    xpReward: 80,
    pointsReward: 40,
    tier: "bronze",
  },
  {
    id: "level_10",
    code: "level_10",
    title: "Silver Smith",
    description: "Reach level 10.",
    xpReward: 0,
    pointsReward: 100,
    tier: "silver",
  },
];
