import type { Achievement } from "@/types";

export const ACHIEVEMENT_SEED: Achievement[] = [
  {
    id: "first_log",
    code: "first_log",
    title: "First meal logged",
    description: "Log your first meal.",
    xpReward: 50,
    pointsReward: 25,
    tier: "bronze",
  },
  {
    id: "streak_3",
    code: "streak_3",
    title: "3-day streak",
    description: "Log food 3 days in a row.",
    xpReward: 75,
    pointsReward: 40,
    tier: "bronze",
  },
  {
    id: "streak_7",
    code: "streak_7",
    title: "7-day streak",
    description: "Log food 7 days in a row.",
    xpReward: 150,
    pointsReward: 80,
    tier: "silver",
  },
  {
    id: "streak_30",
    code: "streak_30",
    title: "30-day streak",
    description: "Log food 30 days in a row.",
    xpReward: 400,
    pointsReward: 200,
    tier: "gold",
  },
  {
    id: "water_7",
    code: "water_7",
    title: "Water goal 7 days",
    description: "Hit your water goal 7 days in a row.",
    xpReward: 120,
    pointsReward: 60,
    tier: "silver",
  },
  {
    id: "weigh_in_4",
    code: "weigh_in_4",
    title: "4 weigh-ins",
    description: "Log your weight 4 times.",
    xpReward: 100,
    pointsReward: 50,
    tier: "silver",
  },
  {
    id: "macro_perfect",
    code: "macro_perfect",
    title: "Macros hit in one day",
    description: "Hit protein, carbs, and fat in one day.",
    xpReward: 80,
    pointsReward: 40,
    tier: "bronze",
  },
  {
    id: "level_10",
    code: "level_10",
    title: "Reach level 10",
    description: "Earn enough XP to reach level 10.",
    xpReward: 0,
    pointsReward: 100,
    tier: "silver",
  },
];
